export const environment = {
  production: true,
  rootPath: window['rootPath'],
  rootPath3: window['rootPath3'],
  // formPath: '',
  // username: 'BL_desk_mgr',
  //  username: 'BL_Tech_officer',
  // username: 'BL_Data_Encoder',
  // username: 'BL_Tech_leader',
  // username: 'berukbb',
  // username: 'Inventory user',
  username: window['_UserName'],
  //username: 'Boss',
  phisicalPath: './assets/i18n/',
  Lang: '10D04E8B-3361-E111-95D5-00E04C05559B',
  certReportPath: window['certReportPath'],
  LetterReportPath: window['LetterReportPath'],
  PaymentReportPath: window['PaymentReportPath'],
  ValidateReportPath: window['ValidateReportPath'],
  GISURL: window['GISURL'],
  layoutPath: './xokaSWCMS/DB/',

  formPath: window['formPath'],
  allformPath: window['allformPath'],
  rootPath2: window['rootPath2'],
};
